# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  å°æœ±çš„ä¸ªäººåšå®¢
subtitle: åˆ†äº«æˆ‘çš„å­¦ä¹ å¿ƒå¾—
name: å°æœ±æœ±
email: 2414138198@qq.com
description: å°æœ±æœ±çš„æŠ€æœ¯åˆ†äº«åšå®¢ã€‚å†…å®¹ä¸»è¦ä¸ºå·¥ä½œå­¦ä¹ è¿‡ç¨‹ä¸­çŸ¥è¯†åˆ†äº«ä»¥åŠè‡ªå·±çš„ä¸€äº›å¿ƒå¾—ä½“ä¼šã€‚
keywords: Spring,Spring Boot,Spring Cloud,å¼€å‘è€…,ç¼–ç¨‹,ä»£ç ,å¼€æº,ITç½‘ç«™,Developer,Programmer,Coder,Java,Python,
encoding: "utf-8"
favicon: ğŸ·

repository: zhuyoulin123/zhuyoulin123.github.io
github_url: https://github.com/zhuyoulin123
url: https://zhuyoulin123.github.io
# enforce_ssl: ityouknow.com

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:

  -
    href: /stock.html
    label: è‚¡ç¥¨
    target: _blank  

  -
    href: /money.html
    label: æŒ£é’±
    target: _self   

  -
    href: /it.html
    label: æ·±åº¦
    target: _self

  -
    href: /life.html
    label: æ•…äº‹
    target: _self

  -
    href: /arch.html
    label: æ¶æ„
    target: _self

  -
    href: /link.html
    label: å‹é“¾
    target: _self

  -
    href: /about.html
    label: å…³äº
    target: _self

# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /spring-boot.html
    label: Spring Boot
    target: _self
    subnav:

      -
        subHref: /spring-boot.html
        subLabel: Spring Boot

      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud

  -
    href: /spring-boot.html
    label: Java
    target: _blank
    subnav:

      -
        subHref: /java.html
        subLabel: Jvm ç³»åˆ—æ–‡ç« 
        
      -
        subHref: /spring-boot.html
        subLabel: Java æå®¢æŠ€æœ¯
        target: _blank

  -
    
    href: /python.html
    label: Python
    subnav:

      -
        subHref: /python.html
        subLabel: Python æ•™ç¨‹
        
      -
        subHref: /spring-boot.html
        subLabel: Python æŠ€æœ¯
        target: _blank

  -
    href: /archives.html
    label: Archives
    target: _self



# labels. my blog key words
labels:

  -
    href: /payment.html
    label: Pay     
    target: _self

  -
    href: /fastdfs.html
    label: FastDFS
    target: _blank

  -
    href: /mongodb.html
    label: MongoDB
    target: _blank

  -
    href: /docker.html
    label: Docker
    target: _blank

  -
    href: /open-source.html
    label: Code  
    target: _blank

  -
    href: /gitchat.html
    label: Chat
    target: _blank


# selected articles
classes:

  -
    href: /cartoon.html
    name: ä¸ä¼šç¬‘é’å¹´
    describe: å†…å¿ƒæ²‰ç¨³ ï¼Œæ”¾è¡ä¸ç¾ã€‚

  -
    href: /life.html
    name: æˆ‘çš„æ•…äº‹
    describe: ç”Ÿæ´»å°±æ˜¯æ•…äº‹ï¼Œæ•…äº‹å°±æ˜¯ç”Ÿæ´»

  -
    href: /it.html
    name: ITè¡Œä¸šæ·±åº¦æŠ¥é“
    describe: ITå¤§ä½¬ï¼Œäº’è”ç½‘çŸ¥åå…¬å¸çš„æ•…äº‹




# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
# comments_provider: gitalk
# !!!é‡è¦!!! è¯·ä¿®æ”¹ä¸‹é¢è¿™äº›ä¿¡æ¯ä¸ºä½ è‡ªå·±ç”³è¯·çš„
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
# disqus:
    # username: ityouknow
# https://imsun.net/posts/gitment-introduction/
# gitment:
    # owner: ityouknow
    # repo: blog-comments
    # oauth:
        # client_id: 61bfc53d957e74e78f8f
        # client_secret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# https://github.com/gitalk/gitalk#install
# gitalk:
    # owner: ityouknow
    # repo: blog-comments
    # clientID: 61bfc53d957e74e78f8f
    # clientSecret: 31c61e66cdcc9ada8db2267ee779d0bdafac434c
# åœ¨ä½¿ç”¨å…¶ å®ƒè¯„è®ºç»„ä»¶æ—¶å¯ç‚¹å‡»æ˜¾ç¤º Disqus
# lazy_load_disqus : true
